// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bnGmFYN1UUt3iuCFsqhSBQ
// Component: cQBL5E8C3y7e

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bnGmFYN1UUt3iuCFsqhSBQ/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: cQBL5E8C3y7e/css

import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: dbzvZSfCZPJL/icon

createPlasmicElementProxy;

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};
export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};
type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};
type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "stars",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.stars
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant($state, "stars", "five"),
          [sty.rootstars_four]: hasVariant($state, "stars", "four"),
          [sty.rootstars_one]: hasVariant($state, "stars", "one"),
          [sty.rootstars_three]: hasVariant($state, "stars", "three"),
          [sty.rootstars_two]: hasVariant($state, "stars", "two"),
          [sty.rootstars_zero]: hasVariant($state, "stars", "zero")
        }
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__pdeyQ, {
            [sty.svgstars_five__pdeyQhs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_zero__pdeyQjVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__nsNyr, {
            [sty.svgstars_five__nsNyrHs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__nsNyrM17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__nsNyr4Xre]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__nsNyrnNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__nsNyrBk9Y2]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__nsNyrjVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__wrt10, {
            [sty.svgstars_five__wrt10Hs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__wrt10M17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__wrt104Xre]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__wrt10NNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__wrt10Bk9Y2]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__wrt10JVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__oD4DH, {
            [sty.svgstars_five__oD4DHhs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__oD4DHm17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__oD4DH4Xre]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__oD4DHnNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__oD4DHbk9Y2]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__oD4DHjVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg___7CkEq, {
            [sty.svgstars_five___7CkEqhs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four___7CkEqm17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one___7CkEq4Xre]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three___7CkEQnNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two___7CkEqbk9Y2]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero___7CkEQjVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__lj73F, {
            [sty.svgstars_five__lj73FHs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__lj73FM17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_one__lj73F4Xre]: hasVariant($state, "stars", "one"),
            [sty.svgstars_three__lj73FnNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__lj73FBk9Y2]: hasVariant($state, "stars", "two"),
            [sty.svgstars_zero__lj73FjVic]: hasVariant($state, "stars", "zero")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__g74Xp, {
            [sty.svgstars_five__g74XpHs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__g74XpM17Vb]: hasVariant(
              $state,
              "stars",
              "four"
            ),
            [sty.svgstars_three__g74XpnNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            ),
            [sty.svgstars_two__g74XpBk9Y2]: hasVariant($state, "stars", "two")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__tR9S, {
            [sty.svgstars_five__tR9SHs6Iz]: hasVariant($state, "stars", "five"),
            [sty.svgstars_four__tR9SM17Vb]: hasVariant($state, "stars", "four"),
            [sty.svgstars_three__tR9SNNSkP]: hasVariant(
              $state,
              "stars",
              "three"
            )
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__wkEg2, {
            [sty.svgstars_five__wkEg2Hs6Iz]: hasVariant(
              $state,
              "stars",
              "five"
            ),
            [sty.svgstars_four__wkEg2M17Vb]: hasVariant($state, "stars", "four")
          })}
          role={"img"}
        />

        <Icon13Icon
          className={classNames(projectcss.all, sty.svg__wBlzx, {
            [sty.svgstars_five__wBlzxHs6Iz]: hasVariant($state, "stars", "five")
          })}
          role={"img"}
        />
      </Stack__>
      {renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRatings__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
